var source =
    {
        "kullaniciadi": "Kullanıcı Adı",
        "sifre": "Şifre",
        "giris": "Giriş",
        "iptal": "İptal",
        "yukleniyor": "Yükleniyor...",
        "cikisyapiliyor": "Çıkış Yapılıyor..",
        "cikis": "Çıkış",
        "ayarlar": "Ayarlar",
        "hesap": "Hesap",
        "uygulamaayarlari": "Uygulama Ayarları",
        "kullaniciayarlari": "Kullanıcı Ayarları",
        "mobilbilgiyonetimsistemi": "Mobil Bilgi Sistemi",
        "anamenu": "Ana menü",
        "geri": "Geri",
        "adsoyad": "Adı Soyadı",
        "adi": " Adı",
        "soyadi": "Soyadı",
        "aciklama": "Açıklama",
        "tarih": "Tarih",
        "saat": "Saat",
        "sure": "Süre",
        "oturumukapat": "Oturumu Kapat",
        "girisinfo1": "Randevu ve Arayan Takip Sistemi'ne,",
        "girisinfo2": "- Sizin için tanımlanan kullanıcı adı ve şifrenizi girerek giriş yapabilirsiniz.",
        "girisinfo3": "- Beni hatırla butonuyla bir kez girmiş olduğunuz kullanıcı ve şifrenizi tekrar girmeniz önlenmiş olur.",
        "yil": "Yıl",
        "kayitbulundu": "kayıt bulundu.",
        "baslangictarihi": "Başlangıç Tarihi",
        "bitistarihi": "Bitiş Tarihi",
        "etkinlikadi": "Etkinlik Adı",
        "yer": "Yer",
        "yilsecimi": "Yıl Seçimi",
        "uyari": "Uyarı",
        "randevuvearayantakipsistemi": "Randevu ve Arayan Takip Sistemi",
        "benihatirla": "Beni hatırla",
        "sistemayarlari": "Sistem Ayarları",
        "servisip": "Servis IP Adresi",
        "kaydet": "Kaydet",
        "iptal": "İptal",
        "ipadresinigiriniz": "Yeni IP Adresini Giriniz...",
        "servisipduzenleme": "Servis IP Düzenlemesi",
        "mevcutservisip": "Mevcut Servis IP Adresi",
        "randevular": "Randevular",
        "arayanlar": "Arayanlar",
        "ajanda": "Ajanda",
        "ajandaeditable": "Ajanda Editable",
        "ajandareadonly": "Ajanda ReadOnly",
        "randevukaydibulunamadi": "Randevu kaydı bulunamadı...",
        "resmirandevular": "Resmi Randevular",
        "ozelrandevular": "Özel Randevular",
        "arayankaydibulunamadi": "Arayan kaydı bulunamadı...",
        "bugun": "Bugün",
        "secilenrandevu": "Seçilen Randevu Detayı",
        "secilenarayandetayi": "Seçilen Arayan Detayı",
        "hatirlatma": "Hatırlatma",
        "randevudetaybilgileri": "Randevu Detay Bilgileri",
        "randevuaciklamaekle": "Randevu Açıklama Ekle",
        "arayandetaybilgileri": "Arayan Detay Bilgileri",
        "arayansonuc": "Arayan Sonuç Ekle",
        "burayaaciklamayaziniz": "Buraya açıklama yazınız...",
        "secilenarayan": "Seçilen Arayan",
        "sonuc": "Sonuç",
        "arayansonucekle": "Arayan Sonuç Ekle",
        "telefon": "Telefon",
        "burayasonucyaziniz": "Buraya sonuç yazınız...",
        "yenilemekicincekin": "Yenilemek için çekin",
        "yenileniyor": "Yenileniyor",
        "yenilemekicinbirakin": "Yenilemek için bırakın",
        "randevutipi": "Randevu Tipi",
        "resmiajanda": "Resmi Ajanda",
        "ozelajanda": "Özel Ajanda",
        "ajandatitle": "Ajanda"
    };